[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "autodonate-bulma-theme"
description = "Lightweight autodonate global theme written with Bulma framework!"
version = "0.1.0"
license = "AGPL3"

authors = []

readme = "README.md"

repository = "https://github.com/fire-squad/autodonate-bulma-theme"

[tool.poetry.dependencies]
python = "^3.10"
poetry = "^1"
Django = "^4.0.2"
autodonate = "^0.1.0-alpha.0"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
mypy = "^0.931"

safety = "^1.10"

pytest = "^7.0"
pytest-cov = "^3.0"
pytest-randomly = "^3.11"

sphinx = "^4.4"
sphinx-autodoc-typehints = "^1.17"
sphinxcontrib-apidoc = "^0.3"
furo = "^2022.1.2"
doc8 = "^0.10"
m2r2 = "^0.3"
tomlkit = "^0.10"
toml = "^0.10.2"
